openapi: 3.0.1
info:
  title: Node Public API
  description: ''
  contact:
    email: operators@constellationnetwork.io
  version: 1.0.0
tags:
  - name: Cluster
  - name: Metrics
  - name: Metadata
  - name: Transaction

paths:
  /cluster/info:
    get:
      tags:
        - Cluster
      summary: Get current cluster observation
      responses:
        200:
          description: Cluster observation
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/NodeState'

  /metrics:
    get:
      tags:
        - Metrics
      summary: Get node's metrics
      responses:
        200:
          description: Node's metrics
          content:
            'application/json':
              schema:
                type: object
                properties:
                  metrics:
                    type: object
                    additionalProperties:
                      type: string

  /micrometer-metrics:
    get:
      tags:
        - Metrics
      summary: Get node's micrometer metrics
      responses:
        200:
          description: Node's micrometer metrics
          content:
            'text/plain':
              schema:
                type: string

  /address/{address}:
    get:
      tags:
        - Metadata
      summary: Get wallet balance for given address
      parameters:
        - name: address
          in: path
          description: Address of wallet to return
          required: true
          schema:
            type: string
      responses:
        200:
          description: Wallet balance for given address
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Balance'

  /transaction:
    post:
      tags:
        - Transaction
      summary: Send transaction to network
      requestBody:
        description: Transaction generated by Constellation Wallet
        required: true
        content:
          'application/json':
            schema:
              type: object
      responses:
        200:
          description: Transaction hash
          content:
            'application/json':
              schema:
                type: string
        400:
          description: Invalid transaction

  /transaction/{hash}:
    get:
      tags:
        - Transaction
      summary: Get transaction from node
      parameters:
        - name: hash
          in: path
          description: Hash of transaction to return
          required: true
          schema:
            type: string
      responses:
        200:
          description: Transaction
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Transaction'
        404:
          description: Transaction not found

  /transaction/last-ref/{address}:
    get:
      tags:
        - Transaction
      summary: Get last reference of a given address
      parameters:
        - name: address
          in: path
          description: Address to get the last reference
          required: true
          schema:
            type: string
      responses:
        200:
          description: Last reference
          content:
            'application/json':
              schema:
                type: object
                properties:
                  prevHash:
                    type: string
                  ordinal:
                    type: number
        404:
          description: Last reference not found


components:
  schemas:
    Id:
      type: object
      properties:
        hex:
          type: string
    NodeState:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/Id'
        ip:
          type: object
          properties:
            host:
              type: string
            port:
              type: integer
        status:
          type: string
        reputation:
          type: number
    Balance:
      type: object
      properties:
        balance:
          type: number
        memPoolBalance:
          type: number
        balanceByLatestSnapshot:
          type: number
        rewardsBalance:
          type: number
        reputation:
          type: number
        ancestorBalances:
          type: object
        ancestorReputation:
          type: object
    Transaction:
      type: object

