openapi: 3.0.3
info:
  title: L1 Currency Node - Public API
  description: ""
  contact:
    email: operators@constellationnetwork.io
  version: 2.3.4

tags:
  - name: Cluster
  - name: Currency
  - name: Metric

paths:
  /cluster/info:
    get:
      tags:
        - Cluster
      description: Get Cluster info
      responses:
        200:
          description: Cluster info
          headers:
            X-Id:
              $ref: '../../models/headers/X-Id.yml'
            X-Session-Token:
              $ref: '../../models/headers/X-Session-Token.yml'
            Request-Signature:
              $ref: '../../models/headers/Request-Signature.yml'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '../../models/schemas/Peer.yml'

  /transactions:
    post:
      tags:
        - Currency
      description: Post $Currency transaction
      requestBody:
        description: Signed $Currency transaction
        required: true
        content:
          application/json:
            schema:
              $ref: '../../models/schemas/SignedTransaction.yml'
      responses:
        200:
          description: $Currency transaction has been accepted for processing. Returned hash of the transaction.
          headers:
            X-Id:
              $ref: '../../models/headers/X-Id.yml'
            X-Session-Token:
              $ref: '../../models/headers/X-Session-Token.yml'
            Request-Signature:
              $ref: '../../models/headers/Request-Signature.yml'
          content:
            application/json:
              schema:
                type: object
                properties:
                  hash:
                    $ref: '../../models/schemas/Hash.yml'
        400:
          description: $Currency transaction has been rejected. Returned rejection reason.
          headers:
            X-Id:
              $ref: '../../models/headers/X-Id.yml'
            X-Session-Token:
              $ref: '../../models/headers/X-Session-Token.yml'
            Request-Signature:
              $ref: '../../models/headers/Request-Signature.yml'
          content:
            application/json:
              schema:
                $ref: '../../models/schemas/ErrorResponse.yml'

  /transactions/{hash}:
    get:
      tags:
        - Currency
      description: Get the view of the $Currency transaction for the given hash
      parameters:
        - name: hash
          in: path
          description: Transaction hash
          required: true
          schema:
            $ref: '../../models/schemas/Hash.yml'
      responses:
        200:
          description: Found the transaction with given hash. Returned the view of the transaction
          headers:
            X-Id:
              $ref: '../../models/headers/X-Id.yml'
            X-Session-Token:
              $ref: '../../models/headers/X-Session-Token.yml'
            Request-Signature:
              $ref: '../../models/headers/Request-Signature.yml'
          content:
            application/json:
              schema:
                $ref: '../../models/schemas/TransactionView.yml'
        400:
          description: Transaction with the given hash not found on the node
          headers:
            X-Id:
              $ref: '../../models/headers/X-Id.yml'
            X-Session-Token:
              $ref: '../../models/headers/X-Session-Token.yml'
            Request-Signature:
              $ref: '../../models/headers/Request-Signature.yml'

  /transactions/last-reference/{address}:
    get:
      tags:
        - Currency
      description: Get last transaction reference of the given address
      parameters:
        - name: address
          in: path
          description: Wallet address
          required: true
          schema:
            $ref: '../../models/schemas/Address.yml'
      responses:
        200:
          description: Last $Currency transaction reference for given wallet address
          headers:
            X-Id:
              $ref: '../../models/headers/X-Id.yml'
            X-Session-Token:
              $ref: '../../models/headers/X-Session-Token.yml'
            Request-Signature:
              $ref: '../../models/headers/Request-Signature.yml'
          content:
            application/json:
              schema:
                $ref: '../../models/schemas/TransactionReference.yml'

  /metrics:
    get:
      tags:
        - Metric
      description: Micrometer metrics
      responses:
        200:
          description: Micrometer metrics
          headers:
            X-Id:
              $ref: '../../models/headers/X-Id.yml'
            X-Session-Token:
              $ref: '../../models/headers/X-Session-Token.yml'
            Request-Signature:
              $ref: '../../models/headers/Request-Signature.yml'
          content:
            text/html:
              schema:
                type: string
