openapi: 3.0.1
info:
  title: Node Owner API
  description: ''
  contact:
    email: operators@constellationnetwork.io
  version: 1.0.0
tags:
  - name: BuildInfo
  - name: Metrics
  - name: Network

paths:
  /join:
    post:
      tags:
        - Network
      summary: Join the network
      requestBody:
        description: "Host, port and id of the node to join"
        content:
          'application/json':
            schema:
              type: object
              properties:
                host:
                  type: string
                port:
                  type: number
                id:
                  type: string

      responses:
        200:
          description: Joined request has been sent
  /leave:
    post:
      tags:
        - Network
      summary: Leave the network
      responses:
        200:
          description: Left request has been sent

  /metrics:
    get:
      tags:
        - Metrics
      summary: Get node's metrics
      responses:
        200:
          description: Node's metrics
          content:
            'application/json':
              schema:
                type: object
                properties:
                  metrics:
                    type: object
                    additionalProperties:
                      type: string

  /micrometer-metrics:
    get:
      tags:
        - Metrics
      summary: Get node's micrometer metrics
      responses:
        200:
          description: Node's micrometer metrics
          content:
            'text/plain':
              schema:
                type: string

  /buildInfo:
    get:
      tags:
        - BuildInfo
      summary: Build info
      responses:
        200:
          description: Build info
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/BuildInfo'

  /buildInfo/gitCommit:
    get:
      tags:
        - BuildInfo
      summary: Build info - git commit
      responses:
        200:
          description: Build info - git commit
          content:
            'application/json':
              schema:
                type: string

components:
  schemas:
    BuildInfo:
      type: object
      properties:
        name:
          type: string
        version:
          type: string
        scalaVersion:
          type: string
        sbtVersion:
          type: string
        gitBranch:
          type: string
        gitCommit:
          type: string
        builtAtString:
          type: string
        builtAtMillis:
          type: number
